#dockeer-compose.yml
version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=webapi
    networks:
        - host

        

  mongo-seed:
    env_file:
      - .env
    build:
      context: mongo_seed
      dockerfile: Dockerfile
      args:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
        - MONGO_INITDB_DATABASE=webapi
        - MONGO_URI=mongodb://root:example@mongo:27017/webapi
    container_name: mongo-seed

    depends_on:
      - mongo
    networks:
        - host

  api:
    build:
      context: .
      dockerfile: Dockerfileapi
    container_name: api
    ports:
      - 8002:8002
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_URI=mongodb://root:example@mongo:27017/webapi
    volumes:
      - './server:/server'
    networks:
        - host

  streamlitapp:
    build:
      context: .
      dockerfile: Dockerfilestreamlit
    container_name: streamlitapp
    ports:
      - 8501:8501
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_URI=mongodb://root:example@mongo:27017/webapi
    volumes:
      - './app:/app'
    depends_on:
      - mongo
      - api
    networks:
        - host


networks:
    host:
